// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeRespProto.proto

package com.beebank.java.protobuf;

public final class SubscribeRespProto {
  private SubscribeRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeRespProtoTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.SubscribeRespProtoTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 subReqId = 1;</code>
     */
    int getSubReqId();

    /**
     * <code>optional int32 resCode = 2;</code>
     */
    int getResCode();

    /**
     * <code>optional string desc = 3;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code netty.SubscribeRespProtoTest}
   */
  public  static final class SubscribeRespProtoTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.SubscribeRespProtoTest)
      SubscribeRespProtoTestOrBuilder {
    // Use SubscribeRespProtoTest.newBuilder() to construct.
    private SubscribeRespProtoTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeRespProtoTest() {
      subReqId_ = 0;
      resCode_ = 0;
      desc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SubscribeRespProtoTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              subReqId_ = input.readInt32();
              break;
            }
            case 16: {

              resCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beebank.java.protobuf.SubscribeRespProto.internal_static_netty_SubscribeRespProtoTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beebank.java.protobuf.SubscribeRespProto.internal_static_netty_SubscribeRespProtoTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.class, com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.Builder.class);
    }

    public static final int SUBREQID_FIELD_NUMBER = 1;
    private int subReqId_;
    /**
     * <code>optional int32 subReqId = 1;</code>
     */
    public int getSubReqId() {
      return subReqId_;
    }

    public static final int RESCODE_FIELD_NUMBER = 2;
    private int resCode_;
    /**
     * <code>optional int32 resCode = 2;</code>
     */
    public int getResCode() {
      return resCode_;
    }

    public static final int DESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 3;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string desc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (subReqId_ != 0) {
        output.writeInt32(1, subReqId_);
      }
      if (resCode_ != 0) {
        output.writeInt32(2, resCode_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (subReqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, subReqId_);
      }
      if (resCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, resCode_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, desc_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest)) {
        return super.equals(obj);
      }
      com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest other = (com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest) obj;

      boolean result = true;
      result = result && (getSubReqId()
          == other.getSubReqId());
      result = result && (getResCode()
          == other.getResCode());
      result = result && getDesc()
          .equals(other.getDesc());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
      hash = (53 * hash) + getSubReqId();
      hash = (37 * hash) + RESCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.SubscribeRespProtoTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.SubscribeRespProtoTest)
        com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.beebank.java.protobuf.SubscribeRespProto.internal_static_netty_SubscribeRespProtoTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.beebank.java.protobuf.SubscribeRespProto.internal_static_netty_SubscribeRespProtoTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.class, com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.Builder.class);
      }

      // Construct using com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        subReqId_ = 0;

        resCode_ = 0;

        desc_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.beebank.java.protobuf.SubscribeRespProto.internal_static_netty_SubscribeRespProtoTest_descriptor;
      }

      public com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest getDefaultInstanceForType() {
        return com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.getDefaultInstance();
      }

      public com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest build() {
        com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest buildPartial() {
        com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest result = new com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest(this);
        result.subReqId_ = subReqId_;
        result.resCode_ = resCode_;
        result.desc_ = desc_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest) {
          return mergeFrom((com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest other) {
        if (other == com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest.getDefaultInstance()) return this;
        if (other.getSubReqId() != 0) {
          setSubReqId(other.getSubReqId());
        }
        if (other.getResCode() != 0) {
          setResCode(other.getResCode());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int subReqId_ ;
      /**
       * <code>optional int32 subReqId = 1;</code>
       */
      public int getSubReqId() {
        return subReqId_;
      }
      /**
       * <code>optional int32 subReqId = 1;</code>
       */
      public Builder setSubReqId(int value) {
        
        subReqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subReqId = 1;</code>
       */
      public Builder clearSubReqId() {
        
        subReqId_ = 0;
        onChanged();
        return this;
      }

      private int resCode_ ;
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public int getResCode() {
        return resCode_;
      }
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public Builder setResCode(int value) {
        
        resCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public Builder clearResCode() {
        
        resCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 3;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:netty.SubscribeRespProtoTest)
    }

    // @@protoc_insertion_point(class_scope:netty.SubscribeRespProtoTest)
    private static final com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest();
    }

    public static com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeRespProtoTest>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeRespProtoTest>() {
      public SubscribeRespProtoTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SubscribeRespProtoTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeRespProtoTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeRespProtoTest> getParserForType() {
      return PARSER;
    }

    public com.beebank.java.protobuf.SubscribeRespProto.SubscribeRespProtoTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_SubscribeRespProtoTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_SubscribeRespProtoTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SubscribeRespProto.proto\022\005netty\"I\n\026Sub" +
      "scribeRespProtoTest\022\020\n\010subReqId\030\001 \001(\005\022\017\n" +
      "\007resCode\030\002 \001(\005\022\014\n\004desc\030\003 \001(\tB/\n\031com.beeb" +
      "ank.java.protobufB\022SubscribeRespProtob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_SubscribeRespProtoTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_SubscribeRespProtoTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_SubscribeRespProtoTest_descriptor,
        new java.lang.String[] { "SubReqId", "ResCode", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
